/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#afcbff',
        'primary-container': '#0054a6',
        'on-surface': '#191c1e',
        'on-tertiary-fixed-variant': '#005225',
        'on-tertiary-fixed': '#00210b',
        'surface-container-highest': '#e0e3e5',
        'on-error-container': '#93000a',
        'surface-container-low': '#f2f4f6',
        outline: '#727783',
        'on-secondary-container': '#57657a',
        'tertiary-fixed-dim': '#5adf82',
        error: '#ba1a1a',
        'on-surface-variant': '#424751',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#d5e3fc',
        'surface-dim': '#d8dadc',
        'on-background': '#191c1e',
        'surface-tint': '#185eb0',
        'primary-fixed-dim': '#a9c7ff',
        'on-primary-fixed-variant': '#00468c',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#0d1c2e',
        'inverse-primary': '#a9c7ff',
        'surface-variant': '#e0e3e5',
        'surface-container': '#eceef0',
        'surface-bright': '#f7f9fb',
        tertiary: '#004920',
        'on-tertiary-container': '#5fe386',
        surface: '#f7f9fb',
        'inverse-surface': '#2d3133',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#78fc9c',
        'tertiary-container': '#00632e',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eff1f3',
        primary: '#003d7c',
        'primary-fixed': '#d6e3ff',
        'secondary-fixed': '#d5e3fc',
        background: '#f7f9fb',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'on-primary-fixed': '#001b3d',
        'on-secondary-fixed-variant': '#3a485b',
        secondary: '#515f74',
        'outline-variant': '#c2c6d3',
        'secondary-fixed-dim': '#b9c7df',

        // Regional Strategist palette
        navy: {
          900: '#193F72',
          800: '#12305C',
          700: '#2957A2',
        },
        gold: {
          500: '#D7B56D',
          600: '#C4A35A',
          400: '#E0C17A',
        },
        carbon: '#2B2A29',
        steel: {
          500: '#7688A1',
        },
        'rs-border': '#D9DADA',
        'rs-border-muted': '#B2B3B3',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        card: '12px',
        btn: '10px',
        tag: '6px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        serif: ['"DM Serif Display"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      boxShadow: {
        'rs-card': '0 1px 3px rgba(0,0,0,0.04)',
        'rs-card-hover': '0 4px 12px rgba(25,63,114,0.06)',
        'rs-card-raised': '0 8px 24px rgba(25,63,114,0.08)',
        'rs-gold': '0 4px 24px rgba(215,181,109,0.25)',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        'rs-fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'rs-pop-in': {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '60%': { transform: 'scale(1.1)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'rs-float-1': {
          '0%,100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'rs-float-2': {
          '0%,100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'rs-float-3': {
          '0%,100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        'rs-pulse-outer': {
          '0%,100%': { transform: 'scale(1)', opacity: '0.15' },
          '50%': { transform: 'scale(1.15)', opacity: '0.05' },
        },
        'rs-pulse-middle': {
          '0%,100%': { transform: 'scale(1)', opacity: '0.3' },
          '50%': { transform: 'scale(1.08)', opacity: '0.15' },
        },
        'rs-pulse-inner': {
          '0%,100%': { transform: 'scale(1)', opacity: '0.6' },
          '50%': { transform: 'scale(1.04)', opacity: '0.4' },
        },
        'rs-slow-spin': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'rs-subtle-pulse': {
          '0%,100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(215,181,109,0.35)' },
          '50%': { transform: 'scale(1.05)', boxShadow: '0 0 0 6px rgba(215,181,109,0)' },
        },
      },
      animation: {
        'rs-fade-in-up': 'rs-fade-in-up 400ms cubic-bezier(0.4,0,0.2,1)',
        'rs-pop-in': 'rs-pop-in 300ms cubic-bezier(0.4,0,0.2,1)',
        'rs-float-1': 'rs-float-1 5s ease-in-out infinite',
        'rs-float-2': 'rs-float-2 6s ease-in-out infinite 0.5s',
        'rs-float-3': 'rs-float-3 7s ease-in-out infinite 1s',
        'rs-pulse-outer': 'rs-pulse-outer 2s ease-in-out infinite',
        'rs-pulse-middle': 'rs-pulse-middle 2s ease-in-out infinite 0.2s',
        'rs-pulse-inner': 'rs-pulse-inner 2s ease-in-out infinite 0.4s',
        'rs-slow-spin': 'rs-slow-spin 8s linear infinite',
        'rs-subtle-pulse': 'rs-subtle-pulse 1.6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
