/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#afcbff',
        'primary-container': '#0054a6',
        'on-surface': '#191c1e',
        'on-tertiary-fixed-variant': '#005225',
        'on-tertiary-fixed': '#00210b',
        'surface-container-highest': '#e0e3e5',
        'on-error-container': '#93000a',
        'surface-container-low': '#f2f4f6',
        outline: '#727783',
        'on-secondary-container': '#57657a',
        'tertiary-fixed-dim': '#5adf82',
        error: '#ba1a1a',
        'on-surface-variant': '#424751',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#d5e3fc',
        'surface-dim': '#d8dadc',
        'on-background': '#191c1e',
        'surface-tint': '#185eb0',
        'primary-fixed-dim': '#a9c7ff',
        'on-primary-fixed-variant': '#00468c',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#0d1c2e',
        'inverse-primary': '#a9c7ff',
        'surface-variant': '#e0e3e5',
        'surface-container': '#eceef0',
        'surface-bright': '#f7f9fb',
        tertiary: '#004920',
        'on-tertiary-container': '#5fe386',
        surface: '#f7f9fb',
        'inverse-surface': '#2d3133',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#78fc9c',
        'tertiary-container': '#00632e',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eff1f3',
        primary: '#003d7c',
        'primary-fixed': '#d6e3ff',
        'secondary-fixed': '#d5e3fc',
        background: '#f7f9fb',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'on-primary-fixed': '#001b3d',
        'on-secondary-fixed-variant': '#3a485b',
        secondary: '#515f74',
        'outline-variant': '#c2c6d3',
        'secondary-fixed-dim': '#b9c7df',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
