import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";
import { join } from "node:path";

const projectRoot = process.cwd();

function readProjectFile(relativePath) {
  return readFileSync(join(projectRoot, relativePath), "utf8");
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

test("root layout uses the editorial font stack and product metadata", () => {
  const layout = readProjectFile("app/layout.tsx");

  assert.match(layout, /Playfair_Display|Manrope/);
  assert.match(layout, /Source_Sans_3|Inter/);
  assert.match(layout, /JetBrains_Mono/);
  assert.match(layout, /EduPulse/);
  assert.doesNotMatch(layout, /Create Next App/);
  assert.doesNotMatch(layout, /Generated by create next app/i);
});

test("root layout suppresses hydration noise on document nodes", () => {
  const layout = readProjectFile("app/layout.tsx");

  assert.match(layout, /<html[\s\S]*suppressHydrationWarning/);
  assert.match(layout, /<body[^>]*suppressHydrationWarning/);
});

test("global styles expose editorial design tokens and data-theme dark mode", () => {
  const stylesheet = readProjectFile("app/globals.css");

  for (const token of [
    "--bg-primary",
    "--bg-secondary",
    "--bg-card",
    "--text-primary",
    "--text-secondary",
    "--accent",
    "--accent-hover",
    "--border",
  ]) {
    assert.match(stylesheet, new RegExp(escapeRegExp(token)));
  }

  assert.match(stylesheet, /\[data-theme="dark"\]/);
});

test("landing page and docs no longer ship the stock create-next-app scaffold", () => {
  const landingPage = readProjectFile("app/page.tsx");
  const readme = readProjectFile("README.md");

  for (const stockCopy of [
    "To get started, edit the page.tsx file.",
    "vercel.com/new",
    "nextjs.org/learn",
    "create-next-app",
  ]) {
    assert.doesNotMatch(landingPage, new RegExp(escapeRegExp(stockCopy), "i"));
    assert.doesNotMatch(readme, new RegExp(escapeRegExp(stockCopy), "i"));
  }

  assert.match(readme, /EduPulse/);
  assert.match(landingPage, /redirect\("\/ru"\)/);
});

test("a shared theme toggle exists for the root shell", () => {
  const themeTogglePath = join(projectRoot, "components/layout/ThemeToggle.tsx");

  assert.ok(existsSync(themeTogglePath));

  const themeToggle = readProjectFile("components/layout/ThemeToggle.tsx");
  assert.match(themeToggle, /use client/);
  assert.match(themeToggle, /matchMedia|localStorage|data-theme/);
});

test("client locale UI avoids importing server-backed course content barrels", () => {
  const header = readProjectFile("components/layout/Header.tsx");
  const localizedCourseCard = readProjectFile(
    "components/courses/LocalizedCourseCard.tsx",
  );

  assert.doesNotMatch(header, /from "@\/lib\/course-content"/);
  assert.doesNotMatch(localizedCourseCard, /from "@\/lib\/course-content"/);
});

test("locale auth routes exist and root auth pages are redirect shims", () => {
  for (const relativePath of [
    "app/[locale]/login/page.tsx",
    "app/[locale]/register/page.tsx",
  ]) {
    assert.ok(existsSync(join(projectRoot, relativePath)));
  }

  const loginPage = readProjectFile("app/(auth)/login/page.tsx");
  const registerPage = readProjectFile("app/(auth)/register/page.tsx");

  assert.match(loginPage, /redirect\(/);
  assert.match(registerPage, /redirect\(/);
  assert.doesNotMatch(loginPage, /Welcome Back/);
  assert.doesNotMatch(registerPage, /Create Account/);
});

test("locale-aware course routes and NotebookLM sync workflow exist", () => {
  for (const relativePath of [
    "app/[locale]/layout.tsx",
    "app/[locale]/page.tsx",
    "app/[locale]/courses/page.tsx",
    "app/[locale]/courses/[courseSlug]/page.tsx",
    "app/[locale]/courses/[courseSlug]/learn/[videoSlug]/page.tsx",
    "lib/course-content/index.ts",
    "scripts/notebooklm/sync-course-artifacts.ts",
    "public/videos/digital-culture-bank/episode-1-ru.mp4",
  ]) {
    assert.ok(existsSync(join(projectRoot, relativePath)));
  }

  const packageJson = readProjectFile("package.json");
  assert.match(packageJson, /notebooklm:sync-course/);
});
